# Generated by Django 3.1.3 on 2021-01-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfhandler', '0002_chatmessage_chatroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='verdicts',
            new_name='Language',
        ),
        migrations.RenameModel(
            old_name='levels',
            new_name='Level',
        ),
        migrations.RenameModel(
            old_name='languages',
            new_name='Verdict',
        ),
    ]
