# Generated by Django 3.1.3 on 2021-01-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfhandler', '0003_auto_20210110_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Level',
            new_name='Languages',
        ),
        migrations.RenameModel(
            old_name='Verdict',
            new_name='Levels',
        ),
        migrations.RenameModel(
            old_name='Language',
            new_name='Verdicts',
        ),
    ]
